baseurl = "/"
languageCode = "en-us"
paginate = 5
theme = "terminal"
[languages.en]
copyright = "©2019 Jeremy Bunting. Opinions are mine, not my employer's"
keywords = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
subtitle = "Thoughts and code from tech guy Jeremy Bunting"
title = "qbunt.com"
[[languages.en.menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/qbunt"
[[languages.en.menu.main]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/jeremybunting/"
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "work"
name = "Work"
url = "https://work.jeremybunting.com"
[languages.en.params.logo]
logoHomeLink = "/"
logoText = "Buntlog"
[params]
centerTheme = true
contentTypeName = "posts"
fullWidthTheme = false
showMenuItems = 4
themeColor = "red"
