backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/img/uploads"
media_library:
  name: uploads
public_folder: "/img/uploads"
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Media", name: "media", widget: "file"
             media_library:
               config:
                 multiple: true}
